package br.com.danielwisky.pibbaeta.dao;

import java.util.Map;
import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

  private final DaoConfig feedbackDaoConfig;
  private final DaoConfig pedidoOracaoDaoConfig;
  private final DaoConfig programacaoDaoConfig;

  private final FeedbackDao feedbackDao;
  private final PedidoOracaoDao pedidoOracaoDao;
  private final ProgramacaoDao programacaoDao;

  public DaoSession(Database db, IdentityScopeType type,
      Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
          daoConfigMap) {
    super(db);

    feedbackDaoConfig = daoConfigMap.get(FeedbackDao.class).clone();
    feedbackDaoConfig.initIdentityScope(type);

    pedidoOracaoDaoConfig = daoConfigMap.get(PedidoOracaoDao.class).clone();
    pedidoOracaoDaoConfig.initIdentityScope(type);

    programacaoDaoConfig = daoConfigMap.get(ProgramacaoDao.class).clone();
    programacaoDaoConfig.initIdentityScope(type);

    feedbackDao = new FeedbackDao(feedbackDaoConfig, this);
    pedidoOracaoDao = new PedidoOracaoDao(pedidoOracaoDaoConfig, this);
    programacaoDao = new ProgramacaoDao(programacaoDaoConfig, this);

    registerDao(Feedback.class, feedbackDao);
    registerDao(PedidoOracao.class, pedidoOracaoDao);
    registerDao(Programacao.class, programacaoDao);
  }

  public void clear() {
    feedbackDaoConfig.clearIdentityScope();
    pedidoOracaoDaoConfig.clearIdentityScope();
    programacaoDaoConfig.clearIdentityScope();
  }

  public FeedbackDao getFeedbackDao() {
    return feedbackDao;
  }

  public PedidoOracaoDao getPedidoOracaoDao() {
    return pedidoOracaoDao;
  }

  public ProgramacaoDao getProgramacaoDao() {
    return programacaoDao;
  }

}
