package br.com.danielwisky.pibbaeta.dao;

import android.os.Parcel;
import android.os.Parcelable;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "FEEDBACK".
 */
@Entity
public class Feedback implements Parcelable {

  @Id(autoincrement = true)
  private Long id;

  @NotNull
  private String descricao;

  // KEEP FIELDS - put your custom fields here
  protected Feedback(Parcel in) {
    id = in.readLong();
    descricao = in.readString();
  }

  public static final Creator<Feedback> CREATOR = new Creator<Feedback>() {
    @Override
    public Feedback createFromParcel(Parcel in) {
      return new Feedback(in);
    }

    @Override
    public Feedback[] newArray(int size) {
      return new Feedback[size];
    }
  };
  // KEEP FIELDS END

  @Generated(hash = 802671868)
  public Feedback() {
  }

  public Feedback(Long id) {
    this.id = id;
  }

  @Generated(hash = 1097612872)
  public Feedback(Long id, @NotNull String descricao) {
    this.id = id;
    this.descricao = descricao;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  @NotNull
  public String getDescricao() {
    return descricao;
  }

  /**
   * Not-null value; ensure this value is available before it is saved to the database.
   */
  public void setDescricao(@NotNull String descricao) {
    this.descricao = descricao;
  }

  // KEEP METHODS - put your custom methods here
  @Override
  public void writeToParcel(Parcel dest, int flags) {
    dest.writeLong(id);
    dest.writeString(descricao);
  }

  @Override
  public int describeContents() {
    return 0;
  }
  // KEEP METHODS END
}