package br.com.danielwisky.pibbaeta.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PEDIDO_ORACAO".
 */
@Entity
public class PedidoOracao {

  @Id(autoincrement = true)
  private Long id;

  @NotNull
  private String nome;
  private String email;
  private String telefone;

  @NotNull
  private String pedido;

  // KEEP FIELDS - put your custom fields here
  // KEEP FIELDS END

  @Generated(hash = 872194074)
  public PedidoOracao() {
  }

  public PedidoOracao(Long id) {
    this.id = id;
  }

  @Generated(hash = 44036797)
  public PedidoOracao(Long id, @NotNull String nome, String email, String telefone,
          @NotNull String pedido) {
      this.id = id;
      this.nome = nome;
      this.email = email;
      this.telefone = telefone;
      this.pedido = pedido;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  @NotNull
  public String getNome() {
    return nome;
  }

  /**
   * Not-null value; ensure this value is available before it is saved to the database.
   */
  public void setNome(@NotNull String nome) {
    this.nome = nome;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getTelefone() {
    return telefone;
  }

  public void setTelefone(String telefone) {
    this.telefone = telefone;
  }

  @NotNull
  public String getPedido() {
    return pedido;
  }

  /**
   * Not-null value; ensure this value is available before it is saved to the database.
   */
  public void setPedido(@NotNull String pedido) {
    this.pedido = pedido;
  }

  // KEEP METHODS - put your custom methods here
  // KEEP METHODS END

}
