package br.com.danielwisky.pibbaeta.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TIPO_PROGRAMACAO".
 */
@Entity
public class TipoProgramacao {

  @Id
  private Long id;

  @NotNull
  private String descricao;

  // KEEP FIELDS - put your custom fields here
  // KEEP FIELDS END

  @Generated(hash = 254417004)
  public TipoProgramacao() {
  }

  public TipoProgramacao(Long id) {
    this.id = id;
  }

  @Generated(hash = 1525903947)
  public TipoProgramacao(Long id, @NotNull String descricao) {
      this.id = id;
      this.descricao = descricao;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  @NotNull
  public String getDescricao() {
    return descricao;
  }

  /**
   * Not-null value; ensure this value is available before it is saved to the database.
   */
  public void setDescricao(@NotNull String descricao) {
    this.descricao = descricao;
  }

  // KEEP METHODS - put your custom methods here
  // KEEP METHODS END

}
